import { getServerSession } from "next-auth";
import type { Metadata } from "next";

import { authOptions } from "~/app/api/auth/[...nextauth]/route";
import SessionProvider from "~/app/_components/SessionProvider";
import Provider from "~/app/_trpc/Provider";

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Provider>{children}</Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
